server:
  port: 8089
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
    register-with-eureka: false
    fetch-registry: true
  instance:
    prefer-ip-address: true
 
