spring:
  profiles:
    active: dev
---
server:
  port: 8089
spring:
  profiles: test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
    register-with-eureka: false
    fetch-registry: true
  instance:
    prefer-ip-address: true
user:
  name: 张三8089
---
server:
  port: 8099
spring:
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
    register-with-eureka: false
    fetch-registry: true
  instance:
    prefer-ip-address: true
user:
  name: 张三8089
